# Project: Ë³Ðò±í
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o SqList.o
LINKOBJ  = main.o SqList.o
LIBS     = -L"I:/DEV_C++/Dev-Cpp/MinGW64/lib" -L"I:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"I:/DEV_C++/Dev-Cpp/MinGW64/include" -I"I:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"I:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"I:/DEV_C++/Dev-Cpp/MinGW64/include" -I"I:/DEV_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"I:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"I:/DEV_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ë³Ðò±í.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

SqList.o: SqList.c
	$(CC) -c SqList.c -o SqList.o $(CFLAGS)
